apiVersion: v1
kind: Pod
metadata:
  name: broker
spec:
  hostNetwork: true
  containers:
    - name: etcd
    image: quay.io/coreos/etcd:v3.0.17
    - name: broker
    image: broker
    imagePullPolicy: Never
    args:
    - "--secure-port=9443"
    - "--authentication-kubeconfig=/all-certs/admin.kubeconfig"
    - "--authorization-kubeconfig=/all-certs/admin.kubeconfig"
    - "--tls-ca-file=/all-certs/ca-bundle.crt"
    - "--client-ca-file=/all-certs/ca-bundle.crt"
    - "--requestheader-username-headers=X-Remote-User"
    - "--requestheader-group-headers=X-Remote-Group"
    - "--requestheader-extra-headers-prefix=X-Remote-Extra-"
    - "--requestheader-client-ca-file=/all-certs/ca-bundle.crt"
    - "--etcd-servers=http://127.0.0.1:2379"
    ports:
    - containerPort: 9443
      hostPort: 9443
    volumeMounts:
    - name: all-certs
      mountPath: /all-certs
      readOnly: true
  volumes:
  - name: all-certs
    hostPath:
      path: /home/bparees/git/gocode/src/github.com/openshift/origin/examples/sample-app/openshift.local.config/master
