apiVersion: v1
kind: ReplicationController
metadata:
  name: brokersdk
  namespace: brokersdk
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: brokersdk
      containers:
      - name: brokersdk
        image: brokersdk
        imagePullPolicy: Never
        args:
        - "--etcd-servers=http://localhost:2379"
        - "--authentication-skip-lookup"
        securityContext:
          runAsUser: 0
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.17
        securityContext:
          runAsUser: 0
